package mimi.core.behavior

import mimi.core.model.*
import mimi.core.command.Command
import mimi.core.command.CommandBuffer
import mimi.core.world.WorldSnapshot

// ── Pipeline Phase ─────────────────────────────────────────────────────────────

enum class Phase {
    INTERPRETATION,      // constraint evaluation, entity filtering
    RESOLUTION,          // game logic decisions
    COMMAND_GENERATION,  // state change intentions
    FEEDBACK             // output triggers (sound, animation, haptic)
}

// ── Event ─────────────────────────────────────────────────────────────────────

sealed interface GameEvent {
    val tick:   Tick
    val source: EntityId?
    val target: EntityId?

    // Input events
    data class Tap(val position: PropertyValue.Vec2,
                   override val tick: Tick,
                   override val source: EntityId? = null,
                   override val target: EntityId? = null)                   : GameEvent

    data class DragStart(val entityId: EntityId, val position: PropertyValue.Vec2,
                         override val tick: Tick,
                         override val source: EntityId? = null,
                         override val target: EntityId? = null)             : GameEvent

    data class DragMove(val entityId: EntityId, val position: PropertyValue.Vec2,
                        val delta: PropertyValue.Vec2,
                        override val tick: Tick,
                        override val source: EntityId? = null,
                        override val target: EntityId? = null)              : GameEvent

    data class Drop(val draggedEntity: EntityId, val dropTargetEntity: EntityId,
                    override val tick: Tick,
                    override val source: EntityId? = null,
                    override val target: EntityId? = null)                  : GameEvent

    data class Hold(val position: PropertyValue.Vec2, val duration: Tick,
                    override val tick: Tick,
                    override val source: EntityId? = null,
                    override val target: EntityId? = null)                  : GameEvent

    data class TracePoint(val position: PropertyValue.Vec2, val progress: Float,
                          override val tick: Tick,
                          override val source: EntityId? = null,
                          override val target: EntityId? = null)            : GameEvent

    data class TraceComplete(val pathId: String, val accuracy: Float,
                             override val tick: Tick,
                             override val source: EntityId? = null,
                             override val target: EntityId? = null)         : GameEvent

    // System events (generated by engine after World commit)
    data class MatchSuccess(override val source: EntityId, override val target: EntityId,
                            override val tick: Tick)                        : GameEvent

    data class MatchFail(override val source: EntityId, override val target: EntityId,
                         val reason: String,
                         override val tick: Tick)                           : GameEvent

    data class ObjectiveProgressed(val objectiveId: ObjectiveId,
                                   override val tick: Tick,
                                   override val source: EntityId? = null,
                                   override val target: EntityId? = null)  : GameEvent

    data class ObjectiveCompleted(val objectiveId: ObjectiveId,
                                  override val tick: Tick,
                                  override val source: EntityId? = null,
                                  override val target: EntityId? = null)   : GameEvent

    data class SceneCompleted(override val tick: Tick,
                              override val source: EntityId? = null,
                              override val target: EntityId? = null)        : GameEvent
}

// ── Behavior Context ──────────────────────────────────────────────────────────

interface BehaviorContext {
    val snapshot: WorldSnapshot
    val tick:     Tick
}

// ── Behavior ──────────────────────────────────────────────────────────────────

interface Behavior {
    val id:         BehaviorId
    val phase:      Phase
    val eventTypes: Set<Class<out GameEvent>>

    // Pure function: same inputs → same output. No side effects.
    fun handle(event: GameEvent, ctx: BehaviorContext): List<Command>
}

// ── Behavior Plugin (registered at engine startup) ────────────────────────────

interface BehaviorPlugin {
    val behaviorId:  BehaviorId
    val phase:       Phase
    val eventTypes:  Set<Class<out GameEvent>>

    fun create(config: Map<String, Any>): Behavior
    fun validateConfig(config: Map<String, Any>): ValidationResult
}

// ── Behavior Registry ─────────────────────────────────────────────────────────

interface BehaviorRegistry {
    fun register(plugin: BehaviorPlugin)
    fun create(ref: BehaviorRef): Behavior
    fun isRegistered(id: BehaviorId): Boolean
    fun validateRef(ref: BehaviorRef): ValidationResult
}
