package mimi.core.behavior

import mimi.core.model.*
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
sealed class GameEvent {
    abstract val tick:   Tick
    abstract val source: EntityId?
    abstract val target: EntityId?

    // ── Input Events ──────────────────────────────────────────────────────────

    @Serializable @SerialName("tap")
    data class Tap(
        val position:      PropertyValue.Vec2,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("drag_start")
    data class DragStart(
        val entityId:      EntityId,
        val position:      PropertyValue.Vec2,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("drag_move")
    data class DragMove(
        val entityId:      EntityId,
        val position:      PropertyValue.Vec2,
        val delta:         PropertyValue.Vec2,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("drop")
    data class Drop(
        val draggedEntity:     EntityId,
        val dropTargetEntity:  EntityId,
        override val tick:     Tick,
        override val source:   EntityId? = null,
        override val target:   EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("hold")
    data class Hold(
        val position:      PropertyValue.Vec2,
        val duration:      Tick,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("trace_point")
    data class TracePoint(
        val position:      PropertyValue.Vec2,
        val progress:      Float,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("trace_complete")
    data class TraceComplete(
        val pathId:        String,
        val accuracy:      Float,
        override val tick: Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    // ── System Events (generated by engine after World commit) ────────────────

    @Serializable @SerialName("match_success")
    data class MatchSuccess(
        override val source: EntityId,
        override val target: EntityId,
        override val tick:   Tick
    ) : GameEvent()

    @Serializable @SerialName("match_fail")
    data class MatchFail(
        override val source: EntityId,
        override val target: EntityId,
        val reason:          String,
        override val tick:   Tick
    ) : GameEvent()

    @Serializable @SerialName("objective_progressed")
    data class ObjectiveProgressed(
        val objectiveId:     ObjectiveId,
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("objective_completed")
    data class ObjectiveCompleted(
        val objectiveId:     ObjectiveId,
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("objective_reverted")
    data class ObjectiveReverted(
        val objectiveId:     ObjectiveId,
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("objective_locked")
    data class ObjectiveLocked(
        val objectiveId:     ObjectiveId,
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("scene_started")
    data class SceneStarted(
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("scene_completed")
    data class SceneCompleted(
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("scene_reset")
    data class SceneReset(
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("hint_triggered")
    data class HintTriggered(
        val entityId:        EntityId?,
        val hintLevel:       Int,
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()

    @Serializable @SerialName("idle_check")
    data class IdleCheck(
        override val tick:   Tick,
        override val source: EntityId? = null,
        override val target: EntityId? = null
    ) : GameEvent()
}
